---
# Main tasks for Apache installation and configuration
- name: Update package cache (Ubuntu)
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Apache HTTP Server
  package:
    name: "{{ apache_package }}"
    state: present

- name: Start and enable Apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
